export const STORAGE_KEYS = {
  SCROLL_TIME: "scrollTime",
  FONT_SIZE: "fontSize",
  NOTIFICATIONS: "notifications",
};

export const FONT_SIZE = {
  MIN: 1,
  MAX: 5,
  DEFAULT: 2,
};

export const UI_SELECTORS = {
  LOADING_LAYER: "loading-layer",
  NAVIGATION_RAIL: "navigation-rail",
  PAGES: ".page",
  TEXT_FIELD: "excludeNums",
  ADD_BUTTON: ".add-button",
  CHECK_IMPORTANT: "check-important-msg",
  CUSTOM_SLIDERS: ".slideBtn",
  LIST_CONTAINER_SWITCH: "list-container-switch",
  OPEN_ADD_DIALOG_BUTTON: "open-add-dialog-btn",
  MSG_LIST: ".msgList",
  OVERVIEW_LIST: ".overviewList",
  LIST_CONTAINER: ".list-container",
  SHOW_LIST_ELEMENTS: "#showList",
  UNREAD_COUNT: "unreadCount",
  COUNT_DISPLAY: "count-display",
  CAROUSEL_TOGGLE_BTN: "toggle-carousel-btn",
  DELETE_BTN: "delete-notification-btn",
  CLOSE_EDIT_BTN: "confirm-edit-btn",
  CHANGE_IMPORTANT_CHECK: "change-important-msg",
  PREV_BTN: "prevNotificationBtn",
  NEXT_BTN: "nextNotificationBtn",
  TOGGLE_BUTTON: "open-nodisturb",
  SCREEN_SAVER: "no-disturb-screen",
  EXIT_BUTTON: "exit-screensaver",
  TIME_DISPLAY: "time-display",
  SCREENSAVER_COUNT_DISPLAY: "screensaver-count",
  SCROLL_TIME_SLIDER: "msgScrollTime",
  CLEAR_ALL_BTN: "clear-all-btn",
  EDIT_NOTIFICATION_BTN: "edit-notification-btn",
  OPEN_INFO_DIALOG_BTN: "open-info-dialog-btn",
  CONFIRM_ADD_BTN: "confirm-add-btn",
  TO_MAIN: "toMain",
  TO_LIST: "toList",
  TO_SETTINGS: "toSettings",
  THEME_AUTO: "theme-auto",
  THEME_LIGHT: "theme-light",
  THEME_DARK: "theme-dark",
  BODY: "body",
  DELETE_NOTIFICATION_BTN: "delete-notification-btn",
};